select
    toUInt8(branch_id)                          as branch_id,
    toInt64(delivery_charge_id)                 as delivery_charge_id,
    {{ hnh_id('delivery_line') }}               as delivery_line,
    {{ hnh_ksa_wall_clock('delivery_date') }}   as delivered_at,
    {{ hnh_id('patient_id') }}                  as patient_id,
    {{ hnh_id('episode_no') }}                  as episode_no,
    {{ hnh_id('admission_no') }}                as admission_no,
    {{ hnh_id('encounter_id') }}                as encounter_id,
    {{ hnh_code('encounter_type') }}            as encounter_type,
    {{ hnh_code('staff_id') }}                  as staff_id,
    {{ hnh_id('ios') }}                         as ios,
    {{ hnh_id('purchaser_code') }}              as purchaser_code,
    {{ hnh_id('package_id') }}                  as package_id,
    {{ hnh_id('doc_id') }}                      as doc_id,
    {{ hnh_str('invoice_no') }}                 as invoice_doc_no,
    {{ hnh_code('cancel_flag') }}               as cancel_flag,
    toInt64OrNull(trimBoth(ifNull(status_reason_code, ''))) as cancel_reason_code,
    {{ hnh_code('bill_to') }}                   as bill_to,
    {{ hnh_code('package_deal_flag') }}         as package_deal_flag,
    {{ hnh_code('attendance_type') }}           as attendance_type,
    {{ hnh_code('product_category_code') }}     as product_category_code,
    toFloat64(ifNull(units_delivered, 0))       as units_delivered,
    toFloat64(ifNull(price_paid_purchaser, 0))  as price_paid_purchaser,
    toFloat64(ifNull(discount_given, 0))        as discount_given,
    toFloat64(ifNull(vat_value, 0))             as vat_value,
    recorded_updated_at                         as updated_at
from {{ hnh_oasis_source('delivery_charge') }} final
