select
    toUInt8(branch_id)                              as branch_id,
    toInt64(visit_id)                               as visit_id,
    {{ hnh_ksa_wall_clock('request_date') }}        as request_at,
    {{ hnh_ksa_wall_clock('visit_date') }}          as visit_at,
    {{ hnh_ksa_wall_clock('stat_end_date') }}       as statement_end_at,
    {{ hnh_ksa_wall_clock('creation_date') }}       as created_at,
    {{ hnh_id('claim_invoice_no') }}                as claim_invoice_no,
    {{ hnh_str('stat_invoice_no') }}                as stat_invoice_no,
    {{ hnh_id('patient_id') }}                      as patient_id,
    nullIf(toInt64OrNull(trimBoth(ifNull(episode_no, ''))), 0) as episode_no,
    {{ hnh_id('purchaser_code') }}                  as purchaser_code,
    {{ hnh_id('contract_no') }}                     as contract_no,
    {{ hnh_code('claim_type') }}                    as claim_type,
    {{ hnh_code('doctor_code') }}                   as doctor_code,
    {{ hnh_code('provider_department_code') }}      as provider_department_code,
    {{ hnh_id('api_trans_id') }}                    as api_trans_id,
    {{ hnh_code('status') }}                        as claim_status,
    {{ hnh_code('res_status') }}                    as res_status,
    {{ hnh_code('submit_claim_outcome') }}          as submit_outcome,
    {{ hnh_flag('canceled') }}                      as is_cancelled,
    {{ hnh_ksa_wall_clock('cancel_date') }}         as cancelled_at,
    toFloat64(ifNull(total_claimed_amount, 0))      as total_claimed_amount,
    toFloat64(ifNull(total_net_amount, 0))          as total_net_amount
from {{ hnh_oasis_source('claim_visit_detail') }} final
