select
    toUInt8(branch_id)                        as branch_id,
    toInt64(patient_id)                       as patient_id,
    {{ hnh_str('pat_name_1') }}               as name_1,
    {{ hnh_str('pat_name_2') }}               as name_2,
    {{ hnh_str('pat_name_3') }}               as name_3,
    {{ hnh_str('pat_name_family') }}          as family_name,
    {{ hnh_str('scnd_pat_name_1') }}          as name_ar_1,
    {{ hnh_str('scnd_pat_name_2') }}          as name_ar_2,
    {{ hnh_str('scnd_pat_name_3') }}          as name_ar_3,
    {{ hnh_str('scnd_pat_name_family') }}     as family_name_ar,
    toDate32(date_of_birth)                   as birth_date,
    {{ hnh_code('sex') }}                     as sex,
    {{ hnh_id('nationality_code') }}          as nationality_code,
    {{ hnh_id('marital_code') }}              as marital_code,
    {{ hnh_id('occupation_code') }}           as occupation_code,
    toDate32(date_registered)                 as registered_date,
    {{ hnh_str('dept_registered') }}          as registered_dept,
    {{ hnh_code('status') }}                  as status,
    {{ hnh_id('patient_category') }}          as patient_category_code,
    {{ hnh_flag('chronic_flag') }}            as is_chronic,
    {{ hnh_flag('at_risk_flag') }}            as is_at_risk,
    {{ hnh_id('new_patient_id') }}            as merged_into_patient_id,
    {{ hnh_str('mobile_no') }}                as mobile_no,
    {{ hnh_str('email_address') }}            as email_address
from {{ hnh_oasis_source('patient_master_data') }} final
