select
    toUInt8(branch_id)                          as branch_id,
    toInt64(appointment_id)                     as appointment_id,
    {{ hnh_julian_to_date('julian_date') }}     as slot_date,
    {{ hnh_id('work_entity') }}                 as work_entity,
    {{ hnh_ksa_wall_clock('start_date') }}      as starts_at,
    {{ hnh_ksa_wall_clock('end_date') }}        as ends_at,
    toInt32(appt_length)                        as slot_minutes,
    {{ hnh_id('patient_id') }}                  as patient_id,
    {{ hnh_id('episode_no') }}                  as episode_no,
    {{ hnh_ksa_wall_clock('time_arrived') }}    as arrived_at,
    {{ hnh_ksa_wall_clock('time_seen') }}       as seen_at,
    {{ hnh_ksa_wall_clock('time_complete') }}   as completed_at,
    {{ hnh_code('consultant') }}                as booked_staff_id,
    {{ hnh_code('treated_by') }}                as treating_staff_id,
    {{ hnh_code('new_followup_flag') }}         as new_followup_flag,
    {{ hnh_id('outcome_code') }}                as outcome_code,
    {{ hnh_id('break_code') }}                  as break_code,
    {{ hnh_flag('walkin_flag') }}               as is_walk_in,
    {{ hnh_flag('virtual') }}                   as is_virtual,
    {{ hnh_flag('on_line_booking') }}           as is_online_booking,
    {{ hnh_str('booked_from') }}                as booked_from,
    {{ hnh_ksa_wall_clock('creation_date') }}   as booked_at,
    recorded_updated_at                         as updated_at
from {{ hnh_oasis_source('appointments') }} final
