name: hnh_dwh
version: "1.0.0"
config-version: 2
profile: hnh_dwh

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

vars:
  hnh_history_start_date: "2022-01-01"
  hnh_ssas_machine_name: "SSAS-SERVER"
  hnh_oasis_as_ref: false

models:
  hnh_dwh:
    hnh:
      +tags: ["hnh"]
      staging:
        +schema: stg
        +materialized: view
        +tags: ["hnh_stg"]
      intermediate:
        +schema: int
        +materialized: table
        +tags: ["hnh_int"]
      marts:
        +schema: gold
        +materialized: table
        +tags: ["hnh_gold"]

data_tests:
  hnh_dwh:
    hnh:
      +tags: ["hnh"]
