name: hnh_dwh
version: "1.0.0"
config-version: 2
profile: hnh_dwh

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

vars:
  hnh_history_start_date: "2022-01-01"
  hnh_ssas_machine_name: "SSAS-SERVER"
  hnh_oasis_as_ref: false
  hnh_oasis_source_only: ['operating_diary_slots', 'operating_slot_details']
  hnh_fusion_as_ref: false
  hnh_head_office_fusion_branch_code: 101
  hnh_head_office_ledger_id: 300000005003375
  hnh_fusion_oasis_feed_source: "300000007046804"

models:
  hnh_dwh:
    hnh:
      +tags: ["hnh"]
      staging:
        +schema: stg
        +materialized: view
        +tags: ["hnh_stg"]
      intermediate:
        +schema: int
        +materialized: table
        +tags: ["hnh_int"]
      marts:
        +schema: gold
        +materialized: table
        +tags: ["hnh_gold"]

data_tests:
  hnh_dwh:
    hnh:
      +tags: ["hnh"]

on-run-end:
  - "{{ hnh_log_run(results) }}"
