"""Write the dbt contracts (column names and ClickHouse types) of every gold.ssas_* view (SSAS plan task 7).

Run after `dbt build --select tag:hnh_ssas` whenever a view's columns change on purpose, then commit the YAML.
Usage: python scripts/gen_view_contracts.py
"""
from pathlib import Path

from ch_env import client

OUT = Path(__file__).resolve().parent.parent / "hnh_dwh" / "models" / "hnh" / "marts" / "ssas" / "_ssas__models.yml"


def main():
    rows = client().query(
        "select table, name, type from system.columns "
        "where database = 'gold' and startsWith(table, 'ssas_') order by table, position"
    ).result_rows
    lines = ["version: 2", "", "# Generated by scripts/gen_view_contracts.py from the built views; do not edit by hand.", "models:"]
    current = None
    for table, name, typ in rows:
        if table != current:
            lines += [f"  - name: {table}", "    config:", "      contract: {enforced: true}", "    columns:"]
            current = table
        lines += [f"      - name: {name}", f'        data_type: "{typ}"']
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUT}: {len({r[0] for r in rows})} views, {len(rows)} columns")


if __name__ == "__main__":
    main()
