"""Layout of the HNH_Analytics model: tables, relationship rules, display names and perspectives
(SSAS spec 4, 5, 7 and planning decisions P11, P13). generate.py combines this with the gold.ssas_* columns."""
from hnh_tmdl import Relationship, Table

TABLES = [
    Table("ssas_dim_date", "Date", "date", "Calendar days 2008-2028 with Gregorian and Hijri attributes; the date table."),
    Table("ssas_dim_time", "Time", "dim", "Minutes of the day with hour, quarter hour and shift."),
    Table("ssas_dim_branch", "Branch", "dim", "Hospital branches 1-8 and Head Office (100)."),
    Table("ssas_dim_care_type", "Care Type", "dim", "Outpatient, emergency, inpatient and other care types."),
    Table("ssas_dim_department", "Department", "dim", "Oasis clinics, wards and service departments with unified department."),
    Table("ssas_dim_staff", "Staff", "dim", "Oasis staff and doctors with specialty; filtered to the user's branches and specialties."),
    Table("ssas_dim_staff_role", "Booked Doctor", "role_copy", "Doctor the encounter was booked with (copy of Staff for this role)."),
    Table("ssas_dim_staff_role", "Admission Treating Doctor", "role_copy", "Treating doctor of the admission (copy of Staff for this role)."),
    Table("ssas_dim_staff_role", "Anaesthetist", "role_copy", "Anaesthetist of the surgery (copy of Staff for this role)."),
    Table("ssas_dim_patient", "Patient", "dim", "Patients per branch without personal identifiers; filtered to the user's branches."),
    Table("ssas_dim_patient_pii", "Patient Details", "dim", "Patient names and identifiers; visible only to users with PII access."),
    Table("ssas_dim_payer", "Payer", "dim", "Purchasers (insurers, companies, cash) with category and MOH flag."),
    Table("ssas_dim_service", "Service", "dim", "Billable services (IOS) with product groups."),
    Table("ssas_dim_product_category", "Product Category", "dim", "Product categories with unified and high-level departments."),
    Table("ssas_dim_admission_source", "Admission Source", "dim", "How the patient was admitted."),
    Table("ssas_dim_appointment_outcome", "Appointment Outcome", "dim", "Appointment and visit outcomes."),
    Table("ssas_dim_discharge_outcome", "Discharge Outcome", "dim", "Discharge outcomes with MOH codes."),
    Table("ssas_dim_eligibility_type", "Eligibility Type", "dim", "Visit eligibility types and free follow-up days."),
    Table("ssas_dim_er_priority", "ER Priority", "dim", "Emergency triage priorities (CTAS) with target minutes."),
    Table("ssas_dim_bed", "Bed", "dim", "Beds with class, classification and critical flag."),
    Table("ssas_dim_procedure_type", "Procedure Type", "dim", "Surgery procedure types."),
    Table("ssas_dim_preauth_outcome", "Pre-auth Outcome", "dim", "Final outcomes of pre-authorisation lines."),
    Table("ssas_dim_nphies_reason", "NPHIES Reason", "dim", "NPHIES adjudication and rejection reasons."),
    Table("ssas_dim_fs_line", "FS Line", "dim", "Financial statement lines with sort orders and display sign."),
    Table("ssas_dim_gl_account", "GL Account", "dim", "Fusion code combinations with natural account and FS line."),
    Table("ssas_dim_gl_period", "GL Period", "dim", "Fusion accounting periods including quarterly adjustment periods."),
    Table("ssas_dim_budget_line", "Budget Line", "dim", "Income statement budget lines and subtotals."),
    Table("ssas_dim_supplier", "Supplier", "dim", "Suppliers from Fusion and Oasis."),
    Table("ssas_dim_item", "Item", "dim", "Inventory items from Fusion and Oasis with item group."),
    Table("ssas_dim_store", "Store", "dim", "Stores and subinventories with store type."),
    Table("ssas_dim_movement_type", "Movement Type", "dim", "Stock movement types with direction and consumption flag."),
    Table("ssas_dim_employee", "Employee", "dim", "Fusion workers (current state) with age and tenure bands."),
    Table("ssas_dim_hr_department", "HR Department", "dim", "Fusion HR departments with unified department."),
    Table("ssas_dim_job", "Job", "dim", "Fusion jobs."),
    Table("ssas_dim_grade", "Grade", "dim", "Fusion grades."),
    Table("ssas_dim_position", "Position", "dim", "Fusion positions."),
    Table("ssas_dim_location", "Location", "dim", "Fusion work locations."),
    Table("ssas_dim_worker_action", "Worker Action", "dim", "HR actions and reasons with movement group."),
    Table("ssas_dim_absence_type", "Absence Type", "dim", "Absence types and plans."),
    Table("ssas_dim_pay_category", "Pay Category", "dim", "Pay categories; visible only to users with pay access."),
    Table("ssas_dim_survey_service", "Survey Service", "dim", "Press Ganey survey services."),
    Table("ssas_dim_survey_question", "Survey Question", "dim", "Survey questions with domain, scale and NPS role."),
    Table("ssas_sec_user_access", "User Access", "security", "Branches, specialties and pay/PII permissions per login (security table)."),
    # Facts and aggregates; the fifth field is the partition column of the large tables (spec 9.3).
    Table("ssas_fact_charge_line", "Charge Lines", "fact", "One Oasis charge line (delivered service or item).", "delivery_date_key"),
    Table("ssas_fact_order_line", "Order Lines", "fact", "One order line with its fulfilment status.", "order_date_key"),
    Table("ssas_fact_stock_movement", "Stock Movements", "fact", "One stock movement line from Oasis or Fusion.", "date_key"),
    Table("ssas_fact_patient_consumption", "Patient Consumption", "fact", "Items consumed by patients with cost and revenue.", "date_key"),
    Table("ssas_fact_claim_line", "Claim Lines", "fact", "One NPHIES claim line per submission.", "statement_end_date_key"),
    Table("ssas_fact_claim_payment", "Claim Payments", "fact", "Payer remittance and advances from NPHIES."),
    Table("ssas_fact_cash_receipt", "Cash Receipts", "fact", "Patient receipts, cancellations and refunds.", "receipt_date_key"),
    Table("ssas_fact_invoice", "Invoices", "fact", "One invoice with statement and approval status.", "invoice_date_key"),
    Table("ssas_fact_revenue_adjustment", "Revenue Adjustments", "fact", "Post-invoice revenue adjustments."),
    Table("ssas_fact_preauth_line", "Pre-auth Lines", "fact", "One pre-authorisation line or payer advance authorisation.", "request_date_key"),
    Table("ssas_agg_episode_billing", "Episode Billing", "fact", "Claimable versus invoiced amount per episode.", "last_delivery_date_key"),
    Table("ssas_fact_encounter", "Encounters", "fact", "One outpatient, emergency or inpatient encounter.", "encounter_date_key"),
    Table("ssas_fact_episode", "Episodes", "fact", "One Oasis episode.", "start_date_key"),
    Table("ssas_fact_admission", "Admissions", "fact", "One inpatient admission with length of stay and outcomes."),
    Table("ssas_fact_bed_occupancy_daily", "Bed Occupancy", "fact", "One bed per day: available and occupied.", "date_key"),
    Table("ssas_fact_surgery", "Surgeries", "fact", "One surgery with times and team."),
    Table("ssas_agg_clinic_capacity_daily", "Clinic Capacity", "fact", "Clinic slots per doctor and day.", "date_key"),
    Table("ssas_fact_target_daily", "Targets", "fact", "Daily targets from the budget.", "date_key"),
    Table("ssas_fact_survey_response", "Survey Responses", "fact", "One Press Ganey survey invitation and its response."),
    Table("ssas_fact_survey_answer", "Survey Answers", "fact", "One answered survey question with NPS band."),
    Table("ssas_fact_gl_journal_line", "GL Journal Lines", "fact", "One Fusion journal line.", "accounting_date_key"),
    Table("ssas_fact_gl_balance_monthly", "GL Balances", "fact", "Monthly opening, movement and closing balance per account."),
    Table("ssas_fact_income_statement_monthly", "Income Statement", "fact", "Monthly actual and budget per budget line."),
    Table("ssas_fact_budget_monthly", "Budget", "fact", "Monthly budget per budget line."),
    Table("ssas_fact_ap_invoice_line", "AP Invoice Lines", "fact", "One payables invoice distribution line."),
    Table("ssas_fact_ap_open_item", "AP Open Items", "fact", "Open payables at the last refresh with ageing bucket."),
    Table("ssas_fact_ap_payment", "AP Payments", "fact", "One supplier payment."),
    Table("ssas_fact_stock_monthly", "Stock Monthly", "fact", "Month-end stock per store and item."),
    Table("ssas_fact_purchase_line", "Purchase Lines", "fact", "One purchase order line."),
    Table("ssas_fact_goods_receipt", "Goods Receipts", "fact", "One goods receipt or return line."),
    Table("ssas_fact_headcount_monthly", "Headcount", "fact", "Month-end headcount snapshot per employee."),
    Table("ssas_fact_worker_movement", "Worker Movements", "fact", "Hires, leavers and changes of employees."),
    Table("ssas_fact_payroll_monthly", "Payroll", "fact", "Monthly pay per employee and pay category; pay access only.", "month_date_key"),
    Table("ssas_fact_leave_balance_monthly", "Leave Balances", "fact", "Leave accrual periods with balance and liability; pay access only."),
    Table("ssas_fact_absence", "Absences", "fact", "One absence entry."),
    Table("ssas_fact_absence_daily", "Absence Days", "fact", "One counted absence day per employee."),
    Table("ssas_agg_staff_productivity_monthly", "Staff Productivity", "fact", "Monthly encounters, revenue and payroll per linked doctor or nurse; pay access only."),
]

DIM_KEYS = {
    "branch_key": ("Branch", "branch_key"),
    "patient_key": ("Patient", "patient_key"),
    "care_type_key": ("Care Type", "care_type_key"),
    "service_key": ("Service", "service_key"),
    "department_key": ("Department", "department_key"),
    "payer_key": ("Payer", "payer_key"),
    "product_category_key": ("Product Category", "product_category_key"),
    "staff_key": ("Staff", "staff_key"),
    "item_key": ("Item", "item_key"),
    "store_key": ("Store", "store_key"),
    "supplier_key": ("Supplier", "supplier_key"),
    "gl_account_key": ("GL Account", "gl_account_key"),
    "period_key": ("GL Period", "period_key"),
    "employee_key": ("Employee", "employee_key"),
    "hr_department_key": ("HR Department", "hr_department_key"),
    "job_key": ("Job", "job_key"),
    "grade_key": ("Grade", "grade_key"),
    "position_key": ("Position", "position_key"),
    "location_key": ("Location", "location_key"),
    "pay_category_key": ("Pay Category", "pay_category_key"),
    "absence_type_key": ("Absence Type", "absence_type_key"),
    "movement_type_key": ("Movement Type", "movement_type_key"),
    "worker_action_key": ("Worker Action", "worker_action_key"),
    "budget_line_key": ("Budget Line", "budget_line_key"),
    "survey_service_key": ("Survey Service", "survey_service_key"),
    "question_key": ("Survey Question", "question_key"),
    "nphies_reason_key": ("NPHIES Reason", "nphies_reason_key"),
    "preauth_outcome_key": ("Pre-auth Outcome", "preauth_outcome_key"),
    "procedure_type_key": ("Procedure Type", "procedure_type_key"),
    "eligibility_type_key": ("Eligibility Type", "eligibility_type_key"),
    "outcome_key": ("Appointment Outcome", "outcome_key"),
    "er_priority_key": ("ER Priority", "er_priority_key"),
    "admission_source_key": ("Admission Source", "admission_source_key"),
    "discharge_outcome_key": ("Discharge Outcome", "discharge_outcome_key"),
    "bed_key": ("Bed", "bed_key"),
}

# (table, column) -> (dimension table, dimension key, active). Spec 5.1 role-playing; 5.2 staff copies.
ROLE_KEYS = {
    ("Charge Lines", "billed_payer_key"): ("Payer", "payer_key", True),
    ("Charge Lines", "episode_payer_key"): ("Payer", "payer_key", False),
    ("Order Lines", "ordering_staff_key"): ("Staff", "staff_key", True),
    ("Order Lines", "ordering_department_key"): ("Department", "department_key", True),
    ("Patient Consumption", "treating_staff_key"): ("Staff", "staff_key", True),
    ("Patient Consumption", "billed_payer_key"): ("Payer", "payer_key", True),
    ("Stock Movements", "transfer_store_key"): ("Store", "store_key", False),
    ("Revenue Adjustments", "billed_payer_key"): ("Payer", "payer_key", True),
    ("Pre-auth Lines", "requesting_staff_key"): ("Staff", "staff_key", True),
    ("Encounters", "treating_staff_key"): ("Staff", "staff_key", True),
    ("Encounters", "booked_staff_key"): ("Booked Doctor", "staff_key", True),
    ("Episodes", "consultant_staff_key"): ("Staff", "staff_key", True),
    ("Admissions", "consultant_staff_key"): ("Staff", "staff_key", True),
    ("Admissions", "treating_staff_key"): ("Admission Treating Doctor", "staff_key", True),
    ("Admissions", "first_department_key"): ("Department", "department_key", True),
    ("Admissions", "last_department_key"): ("Department", "department_key", False),
    ("Admissions", "last_bed_key"): ("Bed", "bed_key", True),
    ("Surgeries", "surgeon_staff_key"): ("Staff", "staff_key", True),
    ("Surgeries", "anaesthetist_staff_key"): ("Anaesthetist", "staff_key", True),
    ("Purchase Lines", "ship_to_store_key"): ("Store", "store_key", True),
    ("Worker Movements", "previous_hr_department_key"): ("HR Department", "hr_department_key", False),
    ("Worker Movements", "previous_job_key"): ("Job", "job_key", False),
    ("Worker Movements", "previous_grade_key"): ("Grade", "grade_key", False),
    ("Worker Movements", "previous_position_key"): ("Position", "position_key", False),
    ("Worker Movements", "previous_location_key"): ("Location", "location_key", False),
    ("GL Account", "fs_line_key"): ("FS Line", "fs_line_key", True),
}

# Spec 5.3: one-to-one, both directions; the security filter flows only Patient -> Patient Details.
EXTRA_RELATIONSHIPS = [Relationship("Patient Details", "patient_key", "Patient", "patient_key", True, True)]

# Facts keep these keys hidden, with no relationship (spec 5: facts are never related to each other).
NO_RELATIONSHIP = {
    ("Survey Responses", "survey_response_key"),
    ("Survey Answers", "survey_response_key"),
}

ACTIVE_DATE = {
    "Charge Lines": "delivery_date_key", "Order Lines": "order_date_key", "Stock Movements": "date_key",
    "Patient Consumption": "date_key", "Claim Lines": "statement_end_date_key", "Claim Payments": "payment_date_key",
    "Cash Receipts": "receipt_date_key", "Invoices": "invoice_date_key", "Revenue Adjustments": "adjustment_date_key",
    "Pre-auth Lines": "request_date_key", "Episode Billing": "last_delivery_date_key",
    "Encounters": "encounter_date_key", "Episodes": "start_date_key", "Admissions": "admit_date_key",
    "Bed Occupancy": "date_key", "Surgeries": "operation_date_key", "Clinic Capacity": "date_key", "Targets": "date_key",
    "Survey Responses": "visit_date_key", "Survey Answers": "visit_date_key",
    "GL Journal Lines": "accounting_date_key", "GL Balances": "period_end_date_key",
    "Income Statement": "month_date_key", "Budget": "month_date_key", "AP Invoice Lines": "accounting_date_key",
    "AP Open Items": "invoice_date_key", "AP Payments": "payment_date_key", "Stock Monthly": "month_date_key",
    "Purchase Lines": "po_date_key", "Goods Receipts": "date_key", "Headcount": "month_date_key",
    "Worker Movements": "action_date_key", "Payroll": "month_date_key",
    "Leave Balances": "accrual_period_date_key", "Absences": "start_date_key", "Absence Days": "date_key",
    "Staff Productivity": "month_date_key",
}

ACTIVE_TIME = {
    "Charge Lines": "delivery_time_key", "Order Lines": "order_time_key", "Cash Receipts": "receipt_time_key",
    "Encounters": "encounter_time_key", "Admissions": "admit_time_key", "Surgeries": "operation_time_key",
}

# Decision P13: explicit display names (date column; columns whose friendly name equals a measure in the same table).
COLUMN_NAMES = {
    ("ssas_dim_date", "date_day"): "Date",
    ("ssas_fact_headcount_monthly", "headcount"): "Headcount Units",
    ("ssas_fact_stock_monthly", "stock_value"): "Stock Value Amount",
    ("ssas_fact_stock_movement", "consumption_cost"): "Consumption Cost Amount",
    ("ssas_fact_claim_line", "claimed_amount"): "Line Claimed Amount",
}

# (view, column) -> sort column. generate.py checks each pair is one-to-one in the data.
SORT_BY = {
    ("ssas_dim_date", "month_name"): "month",
    ("ssas_dim_date", "month_short"): "month",
    ("ssas_dim_date", "day_name"): "day_of_week",
    ("ssas_dim_date", "quarter_name"): "quarter",
    ("ssas_dim_date", "year_month_name"): "year_month",
    ("ssas_dim_date", "hijri_month_name"): "hijri_month",
    ("ssas_dim_time", "time_label"): "time_key",
    ("ssas_dim_budget_line", "budget_line_name"): "sort_order",
    ("ssas_dim_pay_category", "pay_category"): "sort_order",
    ("ssas_dim_movement_type", "movement_type"): "sort_order",
    ("ssas_dim_fs_line", "fs_type"): "type_sort",
    ("ssas_dim_fs_line", "fs_element"): "element_sort",
    ("ssas_dim_fs_line", "fs_category"): "category_sort",
    ("ssas_dim_fs_line", "fs_caption"): "caption_sort",
    ("ssas_dim_fs_line", "fs_line"): "line_sort",
}

# Spec 7. Each perspective gets its facts, every dimension they reach, and Time Calculation.
PERSPECTIVES = {
    "Executive": ["Encounters", "Admissions", "Charge Lines", "Invoices", "Claim Lines", "Income Statement", "Budget",
                  "Targets", "Headcount", "Survey Responses"],
    "Patient Flow": ["Encounters", "Admissions", "Episodes", "Bed Occupancy", "Surgeries", "Clinic Capacity", "Targets"],
    "Revenue Cycle": ["Charge Lines", "Order Lines", "Invoices", "Cash Receipts", "Revenue Adjustments", "Episode Billing"],
    "Claims & Pre-auth": ["Claim Lines", "Claim Payments", "Pre-auth Lines"],
    "Finance": ["GL Journal Lines", "GL Balances", "Income Statement", "Budget", "AP Invoice Lines", "AP Open Items",
                "AP Payments"],
    "Workforce": ["Headcount", "Worker Movements", "Absences", "Absence Days", "Payroll", "Leave Balances",
                  "Staff Productivity"],
    "Supply Chain": ["Stock Movements", "Stock Monthly", "Patient Consumption", "Purchase Lines", "Goods Receipts"],
    "Patient Experience": ["Survey Responses", "Survey Answers"],
    "Patient Details": ["Encounters", "Admissions", "Episodes", "Invoices"],
}
PERSPECTIVE_EXTRA = {"Patient Details": ["Patient Details"]}
# Measures live in _Measures with display folder "<domain>\<topic>" (decision P26). A perspective shows the measures of
# its own domain plus Diagnostics; these override that (None = every measure).
PERSPECTIVE_MEASURE_DOMAINS = {"Executive": None, "Patient Details": ["Patient Flow", "Revenue Cycle"]}
